# Generated by Django 4.1.7 on 2023-11-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_excelfile_reservoir_reservoirs_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoirs',
            name='category',
            field=models.CharField(choices=[('водохранилище', 'водохранилище'), ('реки', 'реки'), ('озера', 'озера'), ('хвостохранилище', 'хвостохранилище')], max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
