# Generated by Django 4.1.7 on 2023-11-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservoirs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dry_residue', models.CharField(max_length=50, verbose_name='Dry residue')),
                ('Mineralization', models.CharField(max_length=50, verbose_name='Mineralization')),
                ('sum_of_cations', models.CharField(max_length=50, verbose_name='Sum of cations')),
                ('iron', models.CharField(max_length=50, verbose_name='Iron')),
                ('sodium_and_potassium', models.CharField(max_length=50, verbose_name='Sodium and Potassium')),
                ('magnesium', models.CharField(max_length=50, verbose_name='Magnesium')),
                ('calcium', models.CharField(max_length=50, verbose_name='Calcium')),
                ('anionsum', models.CharField(max_length=50, verbose_name='Anionsum')),
                ('nitrates', models.CharField(max_length=50, verbose_name='Nitrates')),
                ('sulfates', models.CharField(max_length=50, verbose_name='Sulfates')),
                ('chlorides', models.CharField(max_length=50, verbose_name='Chlorides')),
                ('bicarbonates', models.CharField(max_length=50, verbose_name='Bicarbonates')),
                ('carbonates', models.CharField(max_length=50, verbose_name='Carbonates')),
                ('uploaded_at', models.DateTimeField()),
                ('reservoir', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reservoirs')),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
