# Generated by Django 4.1.7 on 2023-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chemistrydata_dry_residue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistrydata',
            name='Dry_residue',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dry residue'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='Mineralization',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mineralization'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='anionsum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Anionsum'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='bicarbonates',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bicarbonates'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='calcium',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Calcium'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='carbonates',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carbonates'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='chlorides',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chlorides'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='iron',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iron'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='magnesium',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Magnesium'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='nitrates',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nitrates'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='sodium_and_potassium',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sodium and Potassium'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='sulfates',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sulfates'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='sum_of_cations',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum of cations'),
        ),
        migrations.AlterField(
            model_name='chemistrydata',
            name='uploaded_at',
            field=models.DateField(),
        ),
    ]
