# Generated by Django 4.1.7 on 2023-11-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chemistrydata_dry_residue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistrydata',
            name='reservoir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reservoirs'),
        ),
    ]
